"""Streamlit app to display literature comparison outputs (combined dataframe and plots).
Run with: streamlit run literature_comparison/app.py
"""
import streamlit as st
import pandas as pd
from pathlib import Path

st.set_page_config(page_title="GlucoVision — Literature Comparison", layout="wide")

st.title("GlucoVision — Literature Comparison 📊")

base = Path(__file__).resolve().parents[0]
comp_dir = base / "comparison"

# Load combined dataframe
csv_path = comp_dir / "combined_comparison.csv"
if csv_path.exists():
    df = pd.read_csv(csv_path)
else:
    st.error(f"Combined CSV not found at {csv_path}. Please run combined_dataframe.py to generate it.")
    st.stop()

# Sidebar: quick stats
st.sidebar.header("Quick actions")
if st.sidebar.button("Refresh files"):
    st.experimental_rerun()

st.sidebar.markdown("**Download data**")
with open(csv_path, "rb") as f:
    st.sidebar.download_button("Download CSV", f, file_name="combined_comparison.csv")

# Main layout
st.subheader("Combined Comparison Dataframe")
st.dataframe(df, use_container_width=True)

# Show accuracy bar chart image
st.subheader("Accuracy / Performance Comparison")
acc_img = comp_dir / "accuracy_comparison.png"
if acc_img.exists():
    st.image(str(acc_img), use_column_width=True, caption="Accuracy comparison across papers")
else:
    st.warning("Accuracy comparison image not found; run comparison_plots.py")

# Show XAI usage image
st.subheader("Explainable AI Usage (Yes vs No)")
xai_img = comp_dir / "xai_usage_counts.png"
if xai_img.exists():
    st.image(str(xai_img), use_column_width=True, caption="XAI usage counts")
else:
    st.warning("XAI usage image not found; run comparison_plots.py")

# Timeline evolution
st.subheader("Timeline: Traditional ML → Deep Learning → Explainable AI")
time_img = comp_dir / "timeline_evolution.png"
if time_img.exists():
    st.image(str(time_img), use_column_width=True, caption="Evolution timeline")
else:
    st.warning("Timeline image not found; run comparison_plots.py")

# Model usage heatmap
st.subheader("Model Usage Matrix")
heat_img = comp_dir / "model_usage_heatmap.png"
if heat_img.exists():
    st.image(str(heat_img), use_column_width=True, caption="Model usage heatmap")
else:
    st.warning("Heatmap image not found; run model_usage_matrix.py")

st.markdown("---")
st.markdown("**Notes:** Images are generated by the scripts in `literature_comparison/comparison/`. If you update the paper files, re-run `combined_dataframe.py` and the plot scripts.")
